spring:
  application:
    name: notification-service
  cloud:
    function:
      definition: orderConsumer
    stream:
      bindings:
        orderConsumer-in-0: # Consumer binding
          destination: order.events  # Kafka topic name
          group: notification-group
          contentType: application/json # Consumer group
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8085



