spring:
  application:
    name: notification-service
  cloud:
    stream:
      bindings:
        orderConsumer-in-0:
          destination: order.events
          content-type: application/json
      rabbit:
        bindings:
          orderConsumer-in-0:
            consumer:
              auto-bind-dlq: true

server:
  port: 8085

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest