spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  cloud:
    stream:
      bindings:
        orderPublisher-out-0:
          destination: order.events
          content-type: application/json
          group: ${spring.application.name}
      rabbit:
        bindings:
          orderPublisher-out-0:
            producer:
              exchangeType: topic

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
#  datasource:
#    url: jdbc:mysql://localhost:3306/order_db
#    username: springstudent
#    password: springstudent
#
#server:
#  port: 8082
#  error:
#    include-stacktrace: never
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    shutdown:
#      access: unrestricted
#  info:
#    env:
#      enabled: true
#
#info:
#  app:
#    name: "Order"
#    description: "Orders Microservice"
#    version: "1.0"