spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  cloud:
    stream:
      bindings:
        orderCreated-out-0: # Producer binding
          destination: order.events  # Kafka topic name
          contentType: application/json  # Ensures JSON serialization
      kafka:
        binder:
          brokers: localhost:9092

logging:
  level:
    org.springframework.cloud.stream: DEBUG
    org.apache.kafka: DEBUG
#  datasource:
#    url: jdbc:mysql://localhost:3306/order_db
#    username: springstudent
#    password: springstudent
#
#server:
#  port: 8082
#  error:
#    include-stacktrace: never
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    shutdown:
#      access: unrestricted
#  info:
#    env:
#      enabled: true
#
#info:
#  app:
#    name: "Order"
#    description: "Orders Microservice"
#    version: "1.0"